version: '3'
services:
  app:
      build:
          context: ./docker
          dockerfile: Dockerfile
          args:
              WWWGROUP: '${WWWGROUP}'
      extra_hosts:
          - 'host.docker.internal:host-gateway'
      ports:
        - '8000:80'       
        - '5173:5173'

      environment:
          WWWUSER: '${WWWUSER}'
      volumes:
          - '.:/var/www/html'
      networks:
          - laravel-docker

  mysql:
      image: 'mysql/mysql-server:8.0'
      ports:
          - '3306:3306'
      environment:
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: 'laravel'
          MYSQL_USER: 'web'
          MYSQL_PASSWORD: 'web'
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
      volumes:
          - 'mysql-data:/var/lib/mysql'
      networks:
          - laravel-docker
  redis:
      image: redis:7.0.2-alpine
      restart: always
      ports:
        - '6379:6379'
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      command: redis-server --save 20 1 --loglevel warning 
      volumes: 
        - redis_cache:/data
      networks:
          - laravel-docker

  phpmyadmin:
    image:  phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      - PMA_HOST=mysql
    networks:
      - laravel-docker
volumes:
  mysql-data:
  redis_cache:     

networks:
    laravel-docker:
        driver: bridge
